#page title
page_title: SpaceEye App # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
# ios_app_id: 1539851747 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://apps.apple.com/app/spaceeye-satellite-wallpaper/id1539851747
windows_store_link: https://www.microsoft.com/store/apps/9NF3WZ8TT6MN?cid=storebadge&ocid=badge
# playstore_link: # Enter Google Play Store URL.
# presskit_download_link:
#   https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: /assets/space_eye_icon.png
app_name: SpaceEye
app_price: Free
app_description: Live satellite imagery for your Mac or Windows desktop background.

other_installation_link: "#installing"

enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: KYDronePilot
your_link: https://github.com/KYDronePilot
# your_city: Copenhagen
email_address: kydronepilotdev@gmail.com
# facebook_username:
# instagram_username: ebaehr
# twitter_username: ebaehr
github_username: KYDronePilot
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Your desktop background updates throughout the day
    description: |
      New images are downloaded every 20 minutes to 1 hour (depending on the
      view), giving an up-to-date view of the Earth on your desktop.
    fontawesome_icon_name: fas fa-sync

  - title: 10 views from 3 satellites
    description: |
      There are currently 10 views from 3 different weather satellites:
      Himawari-8, GOES-17 (West), and GOES-16 (East).
    fontawesome_icon_name: fas fa-satellite

  - title: High resolution imagery
    description: |
      Each satellite view can be downloaded in 4K resolution (if supported by
      the monitor) for crystal clear background pictures of the Earth.
    fontawesome_icon_name: fas fa-image

  - title: Cross-platform
    description: Can be installed on both macOS and Windows.
    fontawesome_icon_name: fas fa-desktop

  - title: Free and open source
    description: |
      SpaceEye is 100% open source and provided free of charge. Contributions
      are welcome!
    fontawesome_icon_name: fas fa-lock-open

sections:
  - title: Installing
    description: |
      ### Mac

      <a href="https://apps.apple.com/us/app/spaceeye-satellite-wallpaper/id1539851747?mt=12&amp;itsct=apps_box&amp;itscg=30200" style="display: inline-block; overflow: hidden; border-top-left-radius: 13px; border-top-right-radius: 13px; border-bottom-right-radius: 13px; border-bottom-left-radius: 13px; width: 193px; height: 64px;"><img src="/assets/mas_badge_black.svg" alt="Download on the Mac App Store" style="border-top-left-radius: 13px; border-top-right-radius: 13px; border-bottom-right-radius: 13px; border-bottom-left-radius: 13px; width: 193px; height: 64px;" width="193px" height="64px"></a>

      - Download from the **Mac App Store** by clicking the link above (US and Canada
        only).
      - Download from the [latest GitHub
        release](https://github.com/KYDronePilot/SpaceEye/releases/latest)
        (available everywhere):
        - [SpaceEye-1.1.2.dmg](https://github.com/KYDronePilot/SpaceEye/releases/download/v1.1.2/SpaceEye-1.1.2.dmg)
          or
        - [SpaceEye-1.1.2-mac.zip](https://github.com/KYDronePilot/SpaceEye/releases/download/v1.1.2/SpaceEye-1.1.2-mac.zip)


      ### Windows

      <a href="//www.microsoft.com/store/apps/9NF3WZ8TT6MN?cid=storebadge&ocid=badge"><img src="/assets/ms_badge_large.png" alt="Download from the Microsoft Store" width="174px" height="64px"/></a>

      - **Recommended**: Download from the **Microsoft Store** by clicking the link
        above (Microsoft account not needed; US and Canada only).
      - Alternative: Follow the [installation
        instructions](https://github.com/KYDronePilot/SpaceEye/wiki/Installing-on-Windows)
        to download and run the installer from the latest GitHub release (available
        everywhere).
        - **Note**: You will have to dismiss warnings about the download being
          potentially dangerous with this method.

  - title: Acknowledgements
    description: |
      Special thanks to <a
      href="https://www.star.nesdis.noaa.gov/star/index.php">NOAA STAR</a> and
      the <a href="http://rammb.cira.colostate.edu/">Regional and Mesoscale
      Meteorology Branch (RAMMB)</a> of NOAA/NESDIS (located at Colorado State
      University) for hosting the satellite imagery.
  - title: Issues or feature requests?
    description: |
      Create an issue on the <a
      href="https://github.com/KYDronePilot/SpaceEye/issues">Issues page</a>.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: /assets/continental_us_late_afternoon.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#1f1f1f"

link_color: "#4375ca"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#ffffff"
feature_text_color: "#868686"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
